### ISSUE TITLE
0 Employees Identified

### ISSUE THREAD

**Issue by poltys** [gojhonny/InSpy#3]
Hi, 

I have tried both with kali and fedora with several companies and the result is always the same: 

`InSpy 2.0.2`

`2017-03-05 00:35:54 0 Employees identified`
`Completed in 17.0s`

I am missing something? 
Thanks

**Comment by gojhonny** [comment]
This has been fixed in the latest released

**Comment by NoMoreFriends** [comment]
Hi,
I still have the same problem with the last release.

> inspy --empspy /usr/share/inspy/wordlists/title-list-large.txt google

InSpy 2.0.3

2018-01-08 22:04:25 0 Employees identified
Completed in 11.4s
